GET http://localhost:5242/games

###
GET http://localhost:5242/games/4

###
POST http://localhost:5242/games
Content-Type: application/json

{
    "name": "Secret Fighter II",
    "genreId": 1,
    "price": 120,
    "releaseDate": "1999-02-08"
}

###
PUT http://localhost:5242/games/4
Content-Type: application/json

{
    "name": "Secret Fighter II Pro",
    "genreId": 1,
    "price": 120,
    "releaseDate": "1999-02-08"
}

###
DELETE http://localhost:5242/games/2